Rewrite of get_gambl_metadata and new helper functions
morinlab/GAMBLR.results pull request #62
Opened 2024-05-10 01:19 UTC by rdmorin

The main changes are:

* get_gambl_metadata replaces og_get_gambl_metadata functionality but allows backwards compatibility. This function does a variety of checks for consistency in the metadata/biopsy tables and reports issues it finds. 
* check_gene_expression ensures RNA-seq is prioritized the way we want and always deduplicated
* get_gene_expression now relies on both the new functions and their new features

```
exome_priority_meta = get_gambl_metadata(capture_protocol_priority = "Exome")
2908 capture samples are missing a value for protocol. Assuming Exome.                                                                                 
55 biopsies are missing from the biopsy metadata. This should be fixed!                                                                                
affected cohorts:  DLBCL_Weng,DLBCL_Jain
27 biopsies with discrepancies in the pathology field. This should be fixed!
10 biopsies with discrepancies in the time_point field. This should be fixed!
                                                                                                                                                       
> table(exome_priority_meta$protocol)

      Capture      chromium  ctDNA_Genome         Exome        genome        Genome         polyA         PolyA 
           34             3             5          3213            68          1854            11          1108 
Ribodepletion 
         1235 
```

```
not_exome_priority_meta = get_gambl_metadata(capture_protocol_priority = "Capture")
2908 capture samples are missing a value for protocol. Assuming Exome.                                                                                 
55 biopsies are missing from the biopsy metadata. This should be fixed!                                                                                
affected cohorts:  DLBCL_Weng,DLBCL_Jain
27 biopsies with discrepancies in the pathology field. This should be fixed!
10 biopsies with discrepancies in the time_point field. This should be fixed!
                                                                                                                                                       
> table(not_exome_priority_meta$protocol)

      Capture      chromium  ctDNA_Genome         Exome        genome        Genome         polyA         PolyA 
           52             3             5          3195            68          1854            11          1108 
Ribodepletion 
         1235 
```

2024-05-13 19:34 UTC, lkhilton commented on R/get_gambl_metadata2.R
> +#' @param also_normals Set to TRUE to force the return of rows where tissue_status is normal (default is to restrict to tumour)
Can you add a line describing what the `everything` arg does?

2024-05-13 19:45 UTC, lkhilton commented on R/get_gene_expression.R
>      }
```suggestion
    }else{
        if(format == "wide") {
            return(expression_wide)
            } else {
                return(expression_long)
            }
    }
```

2024-05-13 19:50 UTC, lkhilton requested changes
One request for missing documentation, and a suggestion to retain the long data format option for get_gene_expression.

2024-05-13 19:50 UTC, lkhilton commented on R/get_gene_expression.R
>      }
Should we retain the option to return the tidy long format?

2024-05-13 19:55 UTC, lkhilton commented on R/get_gene_expression.R
> +#' @param lazy_join If TRUE, your data frame will also have capture_sample_id and genome_sample_id columns provided. See `check_gene_expression` for more information.
```suggestion
#' @param format Either `wide` or `long`. Wide format returns one column of expression values per gene. Long format returns one column of expression values with the gene stored in a separate column. 
#' @param lazy_join If TRUE, your data frame will also have capture_sample_id and genome_sample_id columns provided. See `check_gene_expression` for more information.
```

2024-05-13 19:55 UTC, lkhilton commented on R/get_gene_expression.R
> +                               engine="grep",
```suggestion
                               engine="grep",
                               format="wide",
```

2024-05-13 22:13 UTC, lkhilton approved these changes

2024-05-14 20:31 UTC, rdmorin commented
Would someone be able to test this again now that I've patched a few more bugs? It was a bit more involved to implement properly but it looks like the format (long/wide) is working as expected.

2024-05-16 18:06 UTC, merged